# Generated by Django 5.0.1 on 2024-04-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_usuario_correoelectronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egreso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
